#pragma once

#define WINDOW_WIDTH 1280
#define WINDOW_HEIGHT 720

#define PARTICLES_COUNT 150
#define PARTICLE_SIZE 5

#define MIN_PARTICLE_VELOCITY -0.1
#define MAX_PARTICLE_VELOCITY 0.1

#define MAX_DRAWING_DISTANCE 150